### ISSUE TITLE
[NEXT] Pick a todo

### ISSUE THREAD

**Issue by henryruhs** [s0md3v/roop#467]
Todos are ordered by priority:

- [ ] Try to get the `TensorrtExecutionProvider` running
- [ ] Submit a PR to `CustomTkinker` to support Drag and Drop - [Related comment](https://github.com/s0md3v/roop/pull/457#issuecomment-158824357)
- [x] Resolve SSL related download issue on MacOS
- [x] ThreadLock for Face Enhancer 
- [x] ThreadPool should allocate frames per future
- [x] Fix color spaces for create video
- [x] mypy
   - [x] Add a `mypi.ini` to ignore existing validations (certain rules per file)
   - [x] Integrate mypi to the CI pipeline
- [x] Use thread pool executor 
- [x] Override fails if output file exists and output path is a directory while using deprecated `-f` or `--face`
- [x] Only one frame processor is applied
   - [x] preview
   - [x] image to image
- [x] Add NSFW filter to preview
- [x] Code of face enhancer needs cleanup as it still refers to source_path and throws error on standalone run
- [x] Override of existing output file not working with `--keep-audio`
- [x] Resolve multi-threading for the face enhancer
- [x]  Evaluate the performance of multi-processing vs. multi-threading for CPU-only - [Related comment](https://github.com/s0md3v/roop/pull/460#issuecomment-1588255341)
- [x] Fix `CTkImage` but `<class 'PIL.ImageTk.PhotoImage'>` in UI
- [x] Implementation check for [frame processors](https://github.com/s0md3v/roop/blob/864e0e914feecaf6dbea71b33916294588632b14/roop/processors/frame/core.py#LL14C2-L14C2) that raise NotImplemented if method does not exist
- [x] Model download in our own Hugging Face space

**Comment by K1llMan** [comment]
> * Submit a PR to CustomTkinker to support Drag and Drop

I think it's dnd related issue. PR created to original repo 
https://github.com/pmgagne/tkinterdnd2/pull/9/commits
https://github.com/Eliav2/tkinterdnd2 not updated for year also.

**Comment by K1llMan** [comment]
Implement something like for each needed function
> hasattr(subclass, 'release') and callable(subclass.release) 

on https://github.com/s0md3v/roop/blob/864e0e914feecaf6dbea71b33916294588632b14/roop/processors/frame/core.py#LL14C2-L14C2
to make sure if module is correct like processor.

**Comment by K1llMan** [comment]
Mechanism for passing external parameters into processors. Parameters can be different in different processors.

**Comment by onlinedear** [comment]
![output](https://github.com/s0md3v/roop/assets/10751712/70843d70-47dc-49d7-93b4-bdcc9805c617)
The face pixel is too low, look forward to an early solution

**Comment by shohag288** [comment]
> Todos are ordered by priority:
> 
> - [ ] Only one frame processor is applied
>    - [x] preview
>    - [ ] image to image
> - [ ] Output video is either too fast or too slow (fps mismatch)
> - [ ] Threading
>    - [ ] Exit gracefully without tons of read/write errors
>    - [x] Dynamic Frame Chunk Selection
> - [ ] mypy
>    - [ ] Add a `mypi.ini` to ignore existing validations (certain rules per file)
>    - [ ] Integrate mypi to the CI pipeline
> - [ ] Resolve SSL related download issue on MacOS / remove the monkey patch
> - [ ] Try to get the `TensorrtExecutionProvider` running
> - [ ] Figure out why `import torch` is needed before a `onnxruntime` usage in order to detect CUDA
> - [ ] Submit a PR to `CustomTkinker` to support Drag and Drop - [Related comment](https://github.com/s0md3v/roop/pull/457#issuecomment-158824357)
> - [ ] Migrate to [tempfile](https://docs.python.org/3/library/tempfile.html) using `dir=temp` to keep temp directory in root
> - [ ] Override fails if output file exists and output path is a directory
> - [x] Add NSFW filter to preview
> - [x] Code of face enhancer needs cleanup as it still refers to source_path and throws error on standalone run
> - [x] Override of existing output file not working with `--keep-audio`
> - [x] Resolve multi-threading for the face enhancer
> - [x]  Evaluate the performance of multi-processing vs. multi-threading for CPU-only - [Related comment](https://github.com/s0md3v/roop/pull/460#issuecomment-1588255341)
> - [x] Fix `CTkImage` but `<class 'PIL.ImageTk.PhotoImage'>` in UI
> - [x] Implementation check for [frame processors](https://github.com/s0md3v/roop/blob/864e0e914feecaf6dbea71b33916294588632b14/roop/processors/frame/core.py#LL14C2-L14C2) that raise NotImplemented if method does not exist
> - [x] Model download in our own Hugging Face space
> 


I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...

my WhatsApp number : +8801314956025

**Comment by henryruhs** [comment]
Close this for now as most todos are done
